version: "3.9" 
services:
  siai-server:
    build: ./server
    image: fabreguesm/siai_server:1.0.6
    ports:
      - "6210:6210"
    environment:
      # Database
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PATH: ${DB_PATH}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # Server
      PORT: ${SERVER_PORT:-6210}
      FRONTEND_URL: ${FRONTEND_URL}
      SECRET_KEY: ${SECRET_KEY}
      PUBLIC_KEY: ${PUBLIC_KEY}
      # Logging
      LOG_FILE: ${LOG_FILE}
      LOG_FORMAT: ${LOG_FORMAT}
      LOG_SIZE: ${LOG_SIZE}
      LOG_INTERVAL: ${LOG_INTERVAL}
    volumes:
      - server-uploads:/app/uploads
      - server-logs:/app/logs
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}  
    networks:
      - traefik   
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:6210 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      placement:
        constraints: ["${NODE}"]

  siai-client:
    build: ./cliente
    image: fabreguesm/siai_cliente:1.0.11
    ports:
      - "6212:6212"
    environment:
      VITE_BACKEND_URL: http://10.250.0.68:6210
      VITE_APP_PORT: ${VITE_APP_PORT:-6212}
    networks:
      - traefik
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:6212 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      placement:
        constraints: ["${NODE}"]
        
networks:
  traefik:
    external:
      name: traefik

volumes:
  server-uploads:
  server-logs:
  siai-flexxus-com-ar:
    name: "${SERVICE_NAME}"
