services:
  siai-server:
    build: ./server
    image: fabreguesm/siai_server:1.0.2
    ports:
      - "6210:6210"
    environment:
      # Database
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PATH: ${DB_PATH}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # Server
      PORT: ${SERVER_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      SECRET_KEY: ${SECRET_KEY}
      PUBLIC_KEY: ${PUBLIC_KEY}
      # Logging
      LOG_FILE: ${LOG_FILE}
      LOG_FORMAT: ${LOG_FORMAT}
      LOG_SIZE: ${LOG_SIZE}
      LOG_INTERVAL: ${LOG_INTERVAL}
    volumes:
      - server-uploads:/app/uploads
      - server-logs:/app/logs
    networks:
      - siai-network
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:6210 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  siai-client:
    build: ./cliente
    image: fabreguesm/siai_cliente:1.0.2
    ports:
      - "6212:80"
    environment:
      VITE_BACKEND_URL: http://localhost:6210
      VITE_APP_PORT: ${VITE_APP_PORT}
    networks:
      - siai-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  siai-network:
    driver: overlay

volumes:
  server-uploads:
  server-logs:
